version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    reviewers:
      - "xjcoan"
    labels:
      - "dependencies"
    open-pull-requests-limit: 0
